NumPy and Pandas are both Python libraries
used in data science and ML.

NumPy:
→ Works with multidimensional arrays (ndarrays)
→ Best for numerical and mathematical operations
→ Very fast for matrix computations
→ Used in deep learning calculations

Pandas:
→ Built on top of NumPy
→ Introduces Series and DataFrame structures
→ Works with any data type including text
→ Best for real world data manipulation
→ Handles missing values easily
→ Can load CSV, Excel, JSON files directly

Key difference:
NumPy → numbers and arrays
Pandas → real world tabular data

In my projects I used Pandas to load and 
clean social media comments and NumPy for 
numerical score calculations!

In [1]:
import pandas as pd

Numpy works only on multidimensional arrays and numbers,it is homegenoues and can't represent or remember the column labels.Here's why pandas has introducted,it is built on top of numpy.Pandas introduces two core structures named series and dataframes which explicitly utilize rows and column labels of dataset.Series structure stores only the single column values mathematically 1D,and dataframe is 2D means it is used to represent multiple columns and rows present on the dataset,helps for data manipulation.

numpy series

In [6]:
s=pd.Series([10,20,30,40,50])
s.name="calories"
print(s)

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [9]:

s.values

array([10, 20, 30, 40, 50], dtype=int64)

Indexing

In [10]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [15]:
fruits=[["mango","apple","guava","sapota","Promogranate"]]

setting index values as fruits names,likewise we can set the index with numbers and other things.Below i have used s.index which sets series data i created with index values of fruits

In [18]:
s.index=fruits
print(s)

mango           10
apple           20
guava           30
sapota          40
Promogranate    50
Name: calories, dtype: int64

In [27]:
s['mango']

10

iloc and loc

The core difference between .loc and .iloc comes down to labels vs. positions."

".iloc is integer-position based. It selects data based on its 0-indexed numerical location, exactly like standard Python list slicing. For example, df.iloc[0:3] will extract rows at positions 0, 1, and 2, excluding the upper bound."

".loc is label-based. It selects data using the actual row and column names. For example, df.loc['mango':'sapota'] will extract everything from 'mango' to 'sapota'. Crucially, .loc includes the upper bound because it’s text-based, and it wouldn't make sense to guess what comes 'just before' a text label.

In [29]:

s.iloc[0:2]

mango    10
apple    20
Name: calories, dtype: int64

loc:label based indexing

In [34]:
s.loc[['mango','sapota']]

mango     10
sapota    40
Name: calories, dtype: int64

In [49]:
fruit_protein={
    "Avocado":2.0,
    "Guava":2.6,
    "Blackberry":2.0,
    "Orange":0.9,
    "Banana":1.1,
    "Apples":0.3,
    "Kiwi":1.1,
    "Pomogranate":1.7,    
    "Mango":0.8,
    "Cherries":1.0
}

In [50]:
s2=pd.Series(fruit_protein,name="Protein")
print(s2)

Avocado        2.0
Guava          2.6
Blackberry     2.0
Orange         0.9
Banana         1.1
Apples         0.3
Kiwi           1.1
Pomogranate    1.7
Mango          0.8
Cherries       1.0
Name: Protein, dtype: float64

Conditional Selection

In [51]:
s2[s2>1]

Avocado        2.0
Guava          2.6
Blackberry     2.0
Banana         1.1
Kiwi           1.1
Pomogranate    1.7
Name: Protein, dtype: float64

logical operators:and,or

In [52]:
s2[(s2>0.82) & (s2<2.0)]

Orange         0.9
Banana         1.1
Kiwi           1.1
Pomogranate    1.7
Cherries       1.0
Name: Protein, dtype: float64

In [53]:
s2[(s2<1.0 ) | (s2>1.5)]

Avocado        2.0
Guava          2.6
Blackberry     2.0
Orange         0.9
Apples         0.3
Pomogranate    1.7
Mango          0.8
Name: Protein, dtype: float64

Modifying the values

In [56]:
s2["Avocado"]=3.1
print(s2)

Avocado        3.1
Guava          2.6
Blackberry     2.0
Orange         0.9
Banana         1.1
Apples         0.3
Kiwi           1.1
Pomogranate    1.7
Mango          0.8
Cherries       1.0
Avacado        3.1
Name: Protein, dtype: float64

Numpy test

In [65]:
import numpy as np
ser=pd.Series(['a',np.nan,1,np.nan,2])
ser.notnull().sum()
print(ser)

0      a
1    NaN
2      1
3    NaN
4      2
dtype: object

Dataframe

In [241]:
data={
    "Names":["Bhargavi","Devi","Shashi","Bhargavi"],
    "Age":[20,21,np.nan,20],
    "Role":["ML","DS","Web development","ML"],
    "Salaries":[60000,80000,np.nan,60000]
}

In [303]:
df=pd.DataFrame(data)
print(df)

      Names   Age             Role  Salaries
0  Bhargavi  20.0               ML   60000.0
1      Devi  21.0               DS   80000.0
2    Shashi   NaN  Web development       NaN
3  Bhargavi  20.0               ML   60000.0

In [304]:
df.head()

      Names   Age             Role  Salaries
0  Bhargavi  20.0               ML   60000.0
1      Devi  21.0               DS   80000.0
2    Shashi   NaN  Web development       NaN
3  Bhargavi  20.0               ML   60000.0

In [305]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Names     4 non-null      object
 1   Age       3 non-null      float64
 2   Role      4 non-null      object
 3   Salaries  3 non-null      float64
dtypes: float64(2), object(2)
memory usage: 260.0+ bytes

head(3)-it selects top 3 rows values

In [306]:
df.head(3)

      Names   Age             Role  Salaries
0  Bhargavi  20.0               ML   60000.0
1      Devi  21.0               DS   80000.0
2    Shashi   NaN  Web development       NaN

df.tail(2)-It prints last 2 rows values

In [307]:
df.tail(2)

      Names   Age             Role  Salaries
2    Shashi   NaN  Web development       NaN
3  Bhargavi  20.0               ML   60000.0

In [308]:
#iloc and loc

df.iloc[0:3,:2]  #rows,columns

      Names   Age
0  Bhargavi  20.0
1      Devi  21.0
2    Shashi   NaN

In [309]:
df.loc[1:3,["Role","Salaries"]]

              Role  Salaries
1               DS   80000.0
2  Web development       NaN
3               ML   60000.0

Dropping the column

for permanent changing we apply inplace,by default its false which means it wont affect on original dataframe,if we want to display with the original value we need to assign it with true

In [310]:
df.drop("Age", axis =1, inplace=False)
df

      Names   Age             Role  Salaries
0  Bhargavi  20.0               ML   60000.0
1      Devi  21.0               DS   80000.0
2    Shashi   NaN  Web development       NaN
3  Bhargavi  20.0               ML   60000.0

In [311]:
df.shape

(4, 4)

In [312]:
df.dtypes

Names        object
Age         float64
Role         object
Salaries    float64
dtype: object

In [313]:
df.describe()

             Age      Salaries
count   3.000000      3.000000
mean   20.333333  66666.666667
std     0.577350  11547.005384
min    20.000000  60000.000000
25%    20.000000  60000.000000
50%    20.000000  60000.000000
75%    20.500000  70000.000000
max    21.000000  80000.000000

Remember:dtypes,shape are attributes/properties(without parathensis),but describe(),info() are functions as they perform some calculations on the dataframe and then displays the output

In [314]:
#Broadcasting
df["Salaries"]=df["Salaries"]+5000 #broadcasted the value to match the column with size and shape of the particular column
df["Salaries"]

0    65000.0
1    85000.0
2        NaN
3    65000.0
Name: Salaries, dtype: float64

In [346]:
df["Salaries"].unique()

array([65000., 85000.,    nan])

In [350]:
df.rename(columns={"Role":"Dept"},inplace=True)

In [351]:
#Counting
df["Dept"].value_counts()

Dept
ML                 2
DS                 1
Web development    1
Name: count, dtype: int64

In [352]:
#creating new column
df["Promoted Salary"]=df["Salaries"] *5
df

,Names,Age,Dept,Salaries,Promoted Salary,first_last_names
0,Bhargavi,80.0,ML,65000.0,325000.0,Bhargavi Yaganti
1,Devi,84.0,DS,85000.0,425000.0,Devi Yaganti
2,Shib,NaN,Web development,NaN,NaN,Shib dev
3,Bhargavi,80.0,ML,65000.0,325000.0,Bhargavi Yaganti

In [353]:
#data cleaning to apply ML concepts on data,and perform other calculations smoothly,accurately
df.isnull().sum()

Names               0
Age                 1
Dept                0
Salaries            1
Promoted Salary     1
first_last_names    0
dtype: int64

In [354]:
#deleting the null value through dropna function,it takes how as parameter where we can assign it with "all"(only deleted the row and column if all the values of that particular rows and columns are NaN) and "any"(deletes even if one row or column has Nan value)
df.dropna(how="all")

,Names,Age,Dept,Salaries,Promoted Salary,first_last_names
0,Bhargavi,80.0,ML,65000.0,325000.0,Bhargavi Yaganti
1,Devi,84.0,DS,85000.0,425000.0,Devi Yaganti
2,Shib,NaN,Web development,NaN,NaN,Shib dev
3,Bhargavi,80.0,ML,65000.0,325000.0,Bhargavi Yaganti

In [355]:
#filling the nan values(missing values)
#we can get rid of this missing values using two methods ,either deleting the row entirly and second one is filling it with value(using fillna method and forward fill,backward fill)
df["Age"].fillna(df["Age"].mean())

0    80.000000
1    84.000000
2    81.333333
3    80.000000
Name: Age, dtype: float64

In [356]:
df["Salaries"].fillna(df["Salaries"].median())

0    65000.0
1    85000.0
2    65000.0
3    65000.0
Name: Salaries, dtype: float64

In [357]:
df["Age"].fillna(method='ffill')

C:\Users\bharg\AppData\Local\Temp\ipykernel_7760\1444085321.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method='ffill')

0    80.0
1    84.0
2    84.0
3    80.0
Name: Age, dtype: float64

In [358]:
df["Age"].fillna(method="bfill")

C:\Users\bharg\AppData\Local\Temp\ipykernel_7760\3345892411.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method="bfill")

0    80.0
1    84.0
2    80.0
3    80.0
Name: Age, dtype: float64

In [359]:
#replacing the column value
df["Names"]=df["Names"].replace("Shashi","Shib")

In [360]:
#Dealing with duplicate values
df_dup=df[df.duplicated(keep='first')]
df_dup

      Names   Age Dept  Salaries  Promoted Salary  first_last_names
3  Bhargavi  80.0   ML   65000.0         325000.0  Bhargavi Yaganti

In [361]:
#lamda function
df["Promoted Salary"]=df["Promoted Salary"].apply(lambda x:x/10 if x>65000 else x)
df

,Names,Age,Dept,Salaries,Promoted Salary,first_last_names
0,Bhargavi,80.0,ML,65000.0,32500.0,Bhargavi Yaganti
1,Devi,84.0,DS,85000.0,42500.0,Devi Yaganti
2,Shib,NaN,Web development,NaN,NaN,Shib dev
3,Bhargavi,80.0,ML,65000.0,32500.0,Bhargavi Yaganti

In [362]:
df["first_last_names"]=["Bhargavi Yaganti","Devi Yaganti","Shib dev","Bhargavi Yaganti"]
df

,Names,Age,Dept,Salaries,Promoted Salary,first_last_names
0,Bhargavi,80.0,ML,65000.0,32500.0,Bhargavi Yaganti
1,Devi,84.0,DS,85000.0,42500.0,Devi Yaganti
2,Shib,NaN,Web development,NaN,NaN,Shib dev
3,Bhargavi,80.0,ML,65000.0,32500.0,Bhargavi Yaganti

In [363]:
#apply and lambda
def multiply(x):
    return x*2
df["Age"]=df["Age"].apply(multiply)
df

,Names,Age,Dept,Salaries,Promoted Salary,first_last_names
0,Bhargavi,160.0,ML,65000.0,32500.0,Bhargavi Yaganti
1,Devi,168.0,DS,85000.0,42500.0,Devi Yaganti
2,Shib,NaN,Web development,NaN,NaN,Shib dev
3,Bhargavi,160.0,ML,65000.0,32500.0,Bhargavi Yaganti

In [373]:
#joins and merge
roles={
    "Dept":["ML","DS","Web development","ML"],
    "Location":["New York","San Francisco","Chicago","India"],
    "Manager":["Laura","Steve","Nina","Heena"],
    "Date":[20-3-26,21-4-26,22-5-26,27-0-26]
}
df1=pd.DataFrame(roles)
pd.concat([df,df1],axis=1)

,Names,Age,Dept,Salaries,Promoted Salary,first_last_names,Dept,Location,Manager,Date
0,Bhargavi,160.0,ML,65000.0,32500.0,Bhargavi Yaganti,ML,New York,Laura,-9
1,Devi,168.0,DS,85000.0,42500.0,Devi Yaganti,DS,San Francisco,Steve,-9
2,Shib,NaN,Web development,NaN,NaN,Shib dev,Web development,Chicago,Nina,-9
3,Bhargavi,160.0,ML,65000.0,32500.0,Bhargavi Yaganti,ML,India,Heena,1

In [374]:
pd.merge(df,df1,on="Dept")

,Names,Age,Dept,Salaries,Promoted Salary,first_last_names,Location,Manager,Date
0,Bhargavi,160.0,ML,65000.0,32500.0,Bhargavi Yaganti,New York,Laura,-9
1,Bhargavi,160.0,ML,65000.0,32500.0,Bhargavi Yaganti,India,Heena,1
2,Devi,168.0,DS,85000.0,42500.0,Devi Yaganti,San Francisco,Steve,-9
3,Shib,NaN,Web development,NaN,NaN,Shib dev,Chicago,Nina,-9
4,Bhargavi,160.0,ML,65000.0,32500.0,Bhargavi Yaganti,New York,Laura,-9
5,Bhargavi,160.0,ML,65000.0,32500.0,Bhargavi Yaganti,India,Heena,1

In [ ]:
#importing dataset